shell /usr/bin/fish
tab_bar_edge top
tab_bar_style powerline
font_size 18
window_padding_width 6
background_opacity 1.0
map alt+t new_tab_with_cwd
map alt+w close_tab
map alt+h previous_tab
map alt+l next_tab
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
font_family IosevkaTerm Nerd Font Mono
foreground #d8d8d8
background #181818
selection_foreground #181818
selection_background #d8d8d8
cursor #d8d8d8
color0 #181818
color1 #ac4242
color2 #90a959
color3 #f4bf75
color4 #6a9fb5
color5 #aa759f
color6 #75b5aa
color7 #d8d8d8
color8 #6b6b6b
color9 #c55555
color10 #aac474
color11 #feca88
color12 #82b8c8
color13 #c28cb8
color14 #93d3c3
color15 #f8f8f8
